Create CONTRIBUTING.md
tinkerbell/tinkerbell.org pull request #143
Opened 2020-09-18 10:23 UTC by rainleander

Signed-off-by: K Rain Leander <rainleander@users.noreply.github.com>

## Description

Contributing notes may be included in README.md or in a separate CONTRIBUTING.md. Expectations around licensing, copyright, and what to expect when contributing to this project should be covered. Tips on what linters and tests are run should be provided so that users can perform these locally. These may differ from project to project, even among common programming languages, based on the ecosystem of the project.

Fixes: https://github.com/tinkerbell/tinkerbell.org/issues/107

2020-09-21 15:09 UTC, mmlb commented
@rainleander We are going to put this in .github repo?

2021-02-22 08:03 UTC, gianarb commented
I think this is out of date! We have a CoC available here https://github.com/tinkerbell/.github/blob/master/CODE_OF_CONDUCT.md

2021-02-22 08:33 UTC, rainleander commented
A code of conduct, a document around the cultural norms / acceptable behaviour, isn't the same as the contributing file which goes into details as to how to contribute to a project. Both are necessary.

2021-06-29 15:51 UTC, mmlb requested changes

2021-06-29 15:51 UTC, mmlb commented on CONTRIBUTING.md
> +Available via [https://github.com/tinkerbell/tinkerbell.org/blob/master/.github/CODE_OF_CONDUCT.md](https://github.com/tinkerbell/tinkerbell.org/blob/master/.github/CODE_OF_CONDUCT.md)
Can you please update this to https://github.com/tinkerbell/.github/blob/master/CODE_OF_CONDUCT.md

2021-08-20 15:45 UTC, tstromberg commented
Closed as obsolete.

2021-08-20 15:45 UTC, closed without merging